create table if not exists public.tenant_activation_keys (
  id bigint generated by default as identity primary key,
  tenant_id varchar(64) not null references public.tenants(id) on delete cascade,
  key_hash varchar(64) not null unique,
  key_last4 varchar(4) not null,
  issued_to_email varchar(255) not null,
  issued_at timestamptz not null default timezone('utc', now()),
  used_at timestamptz null,
  revoked_at timestamptz null,
  metadata jsonb not null default '{}'::jsonb
);

create index if not exists idx_tenant_activation_keys_tenant
  on public.tenant_activation_keys(tenant_id);

create index if not exists idx_tenant_activation_keys_active
  on public.tenant_activation_keys(revoked_at, used_at);

-- Backfill: create an activation key for each existing tenant
insert into public.tenant_activation_keys (
  tenant_id,
  key_hash,
  key_last4,
  issued_to_email,
  issued_at,
  metadata
)
select
  t.id,
  encode(digest(gen_random_uuid()::text, 'sha256'), 'hex'),
  right(encode(digest(gen_random_uuid()::text, 'sha256'), 'hex'), 4),
  'admin@example.com',
  timezone('utc', now()),
  '{}'::jsonb
from public.tenants t
where not exists (
  select 1 from public.tenant_activation_keys k where k.tenant_id = t.id
);