create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

create table if not exists public.tenant_apps (
  id bigint generated by default as identity primary key,
  tenant_id varchar(64) not null,
  app_key varchar(64) not null,
  installed_at timestamptz not null default timezone('utc', now()),
  constraint uq_tenant_app unique (tenant_id, app_key)
);

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  tenant_id varchar(64) not null,
  email varchar(255) not null,
  password_hash varchar(255) not null,
  created_at timestamptz not null default timezone('utc', now()),
  constraint uq_users_tenant_email unique (tenant_id, email)
);

create table if not exists public.inventory_items (
  id bigint generated by default as identity primary key,
  tenant_id varchar(64) not null,
  sku varchar(64) not null,
  name varchar(255) not null,
  description varchar(1000) not null default '',
  quantity_on_hand integer not null default 0,
  reorder_point integer not null default 0,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint uq_inventory_tenant_sku unique (tenant_id, sku)
);

create table if not exists public.inventory_movements (
  id bigint generated by default as identity primary key,
  item_id bigint not null references public.inventory_items(id) on delete cascade,
  tenant_id varchar(64) not null,
  change_amount integer not null,
  reason varchar(255) not null,
  performed_by varchar(255) not null default '',
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.employees (
  id bigint generated by default as identity primary key,
  tenant_id varchar(64) not null,
  full_name varchar(255) not null,
  email varchar(255) not null,
  role varchar(64) not null default 'staff',
  location varchar(128) not null default '',
  is_active integer not null default 1,
  created_at timestamptz not null default timezone('utc', now()),
  constraint uq_employee_tenant_email unique (tenant_id, email)
);

create table if not exists public.time_events (
  id bigint generated by default as identity primary key,
  tenant_id varchar(64) not null,
  employee_id bigint not null references public.employees(id) on delete cascade,
  event_type varchar(32) not null,
  occurred_at timestamptz not null,
  source varchar(32) not null default 'employee',
  reason varchar(255) not null default '',
  created_by varchar(255) not null default '',
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.shifts (
  id bigint generated by default as identity primary key,
  tenant_id varchar(64) not null,
  employee_id bigint not null references public.employees(id) on delete cascade,
  start_at timestamptz not null,
  end_at timestamptz not null,
  location varchar(128) not null default '',
  role varchar(64) not null default 'staff',
  status varchar(32) not null default 'scheduled',
  created_at timestamptz not null default timezone('utc', now()),
  constraint uq_shift_window unique (tenant_id, employee_id, start_at, end_at)
);

create table if not exists public.time_policies (
  id bigint generated by default as identity primary key,
  tenant_id varchar(64) not null unique,
  overtime_daily_hours integer not null default 8,
  overtime_weekly_hours integer not null default 40,
  max_break_minutes integer not null default 60,
  late_tolerance_minutes integer not null default 5,
  early_clock_in_minutes integer not null default 15,
  geofence_required integer not null default 0,
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.timesheet_approvals (
  id bigint generated by default as identity primary key,
  tenant_id varchar(64) not null,
  employee_id bigint not null references public.employees(id) on delete cascade,
  period_start timestamptz not null,
  period_end timestamptz not null,
  status varchar(32) not null default 'pending',
  approved_by varchar(255) not null default '',
  approved_at timestamptz null,
  constraint uq_timesheet_period unique (tenant_id, employee_id, period_start, period_end)
);

create table if not exists public.manager_alerts (
  id bigint generated by default as identity primary key,
  tenant_id varchar(64) not null,
  employee_id bigint null references public.employees(id) on delete set null,
  alert_type varchar(64) not null,
  message varchar(500) not null,
  resolved integer not null default 0,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  tenant_id varchar(64) not null,
  actor varchar(255) not null,
  action varchar(128) not null,
  details varchar(2000) not null default '',
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  tenant_id varchar(64) not null,
  from_user_id bigint not null references public.users(id) on delete cascade,
  to_user_id bigint not null references public.users(id) on delete cascade,
  text varchar(2000) not null,
  created_at timestamptz not null default timezone('utc', now()),
  read_at timestamptz null
);

drop trigger if exists set_inventory_items_updated_at on public.inventory_items;
create trigger set_inventory_items_updated_at
before update on public.inventory_items
for each row execute function public.set_updated_at();

drop trigger if exists set_time_policies_updated_at on public.time_policies;
create trigger set_time_policies_updated_at
before update on public.time_policies
for each row execute function public.set_updated_at();
