create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

create table if not exists public.tenant_apps (
  id bigint generated by default as identity primary key,
  tenant_id varchar(64) not null,
  app_key varchar(64) not null,
  installed_at timestamptz not null default timezone('utc', now()),
  constraint uq_tenant_app unique (tenant_id, app_key)
);

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  tenant_id varchar(64) not null,
  email varchar(255) not null,
  password_hash varchar(255) not null,
  created_at timestamptz not null default timezone('utc', now()),
  constraint uq_users_tenant_email unique (tenant_id, email)
);

create table if not exists public.tenant_memberships (
  id bigint generated by default as identity primary key,
  tenant_id varchar(64) not null,
  user_id bigint not null references public.users(id) on delete cascade,
  role varchar(64) not null default 'staff',
  is_active integer not null default 1,
  created_at timestamptz not null default timezone('utc', now()),
  constraint uq_tenant_membership unique (tenant_id, user_id),
  constraint chk_membership_role check (role in ('admin', 'manager', 'staff')),
  constraint chk_membership_active check (is_active in (0, 1))
);

create table if not exists public.app_sessions (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  tenant_id varchar(64) not null,
  token_hash varchar(64) not null unique,
  expires_at timestamptz not null,
  revoked_at timestamptz null,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_app_sessions_token_hash on public.app_sessions(token_hash);
create index if not exists idx_tenant_memberships_tenant_user on public.tenant_memberships(tenant_id, user_id);

create table if not exists public.pos_menu_categories (
  id bigint generated by default as identity primary key,
  tenant_id varchar(64) not null,
  name varchar(255) not null,
  sort_order integer not null default 0,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint uq_pos_menu_category unique (tenant_id, name)
);

create table if not exists public.pos_menu_items (
  id bigint generated by default as identity primary key,
  tenant_id varchar(64) not null,
  category_id bigint not null references public.pos_menu_categories(id) on delete cascade,
  name varchar(255) not null,
  description varchar(1000) not null default '',
  price_cents integer not null,
  is_active integer not null default 1,
  sort_order integer not null default 0,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint uq_pos_menu_item unique (tenant_id, category_id, name),
  constraint chk_pos_menu_price_positive check (price_cents > 0),
  constraint chk_pos_menu_active check (is_active in (0, 1))
);

create table if not exists public.pos_tables (
  id bigint generated by default as identity primary key,
  tenant_id varchar(64) not null,
  table_number varchar(32) not null,
  guest_count integer not null default 1,
  status varchar(32) not null default 'open',
  assigned_to_user_id bigint null references public.users(id) on delete set null,
  opened_at timestamptz not null default timezone('utc', now()),
  closed_at timestamptz null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint uq_pos_table_number unique (tenant_id, table_number),
  constraint chk_pos_guest_count_nonnegative check (guest_count >= 0),
  constraint chk_pos_table_status check (status in ('open', 'firing', 'ready', 'closed'))
);

create table if not exists public.pos_tickets (
  id bigint generated by default as identity primary key,
  tenant_id varchar(64) not null,
  table_id bigint not null references public.pos_tables(id) on delete cascade,
  status varchar(32) not null default 'open',
  subtotal_cents integer not null default 0,
  printed_at timestamptz null,
  kitchen_note varchar(1000) not null default '',
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint uq_pos_ticket_per_table unique (tenant_id, table_id),
  constraint chk_pos_ticket_status check (status in ('open', 'firing', 'ready', 'closed')),
  constraint chk_pos_subtotal_nonnegative check (subtotal_cents >= 0)
);

create table if not exists public.pos_ticket_items (
  id bigint generated by default as identity primary key,
  tenant_id varchar(64) not null,
  ticket_id bigint not null references public.pos_tickets(id) on delete cascade,
  menu_item_id bigint not null references public.pos_menu_items(id) on delete restrict,
  item_name_snapshot varchar(255) not null,
  unit_price_cents integer not null,
  quantity integer not null default 1,
  line_total_cents integer not null,
  course varchar(64) null,
  seat_label varchar(64) null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint chk_pos_ticket_item_price_positive check (unit_price_cents > 0),
  constraint chk_pos_ticket_item_qty_positive check (quantity > 0),
  constraint chk_pos_ticket_item_total_nonnegative check (line_total_cents >= 0)
);

create table if not exists public.pos_ticket_prints (
  id bigint generated by default as identity primary key,
  tenant_id varchar(64) not null,
  ticket_id bigint not null references public.pos_tickets(id) on delete cascade,
  printed_by varchar(255) not null,
  printed_at timestamptz not null default timezone('utc', now()),
  print_type varchar(64) not null default 'guest_check'
);

create index if not exists idx_pos_menu_categories_tenant_sort on public.pos_menu_categories(tenant_id, sort_order, id);
create index if not exists idx_pos_menu_items_tenant_category_sort on public.pos_menu_items(tenant_id, category_id, sort_order, id);
create index if not exists idx_pos_tables_tenant_status on public.pos_tables(tenant_id, status, table_number);
create index if not exists idx_pos_ticket_items_ticket on public.pos_ticket_items(ticket_id, id);
create index if not exists idx_pos_ticket_prints_ticket on public.pos_ticket_prints(ticket_id, printed_at desc);

create table if not exists public.inventory_items (
  id bigint generated by default as identity primary key,
  tenant_id varchar(64) not null,
  sku varchar(64) not null,
  name varchar(255) not null,
  description varchar(1000) not null default '',
  quantity_on_hand integer not null default 0,
  reorder_point integer not null default 0,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint uq_inventory_tenant_sku unique (tenant_id, sku),
  constraint chk_inventory_qty_nonnegative check (quantity_on_hand >= 0),
  constraint chk_inventory_reorder_nonnegative check (reorder_point >= 0)
);

create table if not exists public.inventory_movements (
  id bigint generated by default as identity primary key,
  item_id bigint not null references public.inventory_items(id) on delete cascade,
  tenant_id varchar(64) not null,
  change_amount integer not null,
  reason varchar(255) not null,
  performed_by varchar(255) not null default '',
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_inventory_items_tenant_name on public.inventory_items(tenant_id, name);
create index if not exists idx_inventory_movements_item on public.inventory_movements(item_id, created_at desc);

create table if not exists public.employees (
  id bigint generated by default as identity primary key,
  tenant_id varchar(64) not null,
  full_name varchar(255) not null,
  email varchar(255) not null,
  role varchar(64) not null default 'staff',
  location varchar(128) not null default '',
  is_active integer not null default 1,
  created_at timestamptz not null default timezone('utc', now()),
  constraint uq_employee_tenant_email unique (tenant_id, email),
  constraint chk_employee_active check (is_active in (0, 1)),
  constraint chk_employee_role check (role in ('admin', 'manager', 'staff'))
);

create table if not exists public.time_events (
  id bigint generated by default as identity primary key,
  tenant_id varchar(64) not null,
  employee_id bigint not null references public.employees(id) on delete cascade,
  event_type varchar(32) not null,
  occurred_at timestamptz not null,
  source varchar(32) not null default 'employee',
  reason varchar(255) not null default '',
  created_by varchar(255) not null default '',
  created_at timestamptz not null default timezone('utc', now()),
  constraint chk_time_event_type check (event_type in ('clock_in', 'clock_out', 'break_start', 'break_end')),
  constraint chk_time_event_source check (source in ('employee', 'manager', 'system'))
);

create index if not exists idx_time_events_tenant_employee_occured on public.time_events(tenant_id, employee_id, occurred_at);

create table if not exists public.shifts (
  id bigint generated by default as identity primary key,
  tenant_id varchar(64) not null,
  employee_id bigint not null references public.employees(id) on delete cascade,
  start_at timestamptz not null,
  end_at timestamptz not null,
  location varchar(128) not null default '',
  role varchar(64) not null default 'staff',
  status varchar(32) not null default 'scheduled',
  created_at timestamptz not null default timezone('utc', now()),
  constraint uq_shift_window unique (tenant_id, employee_id, start_at, end_at),
  constraint chk_shift_status check (status in ('scheduled', 'completed', 'cancelled')),
  constraint chk_shift_range check (end_at > start_at)
);

create index if not exists idx_shifts_tenant_start on public.shifts(tenant_id, start_at);

create table if not exists public.time_policies (
  id bigint generated by default as identity primary key,
  tenant_id varchar(64) not null unique,
  overtime_daily_hours integer not null default 8,
  overtime_weekly_hours integer not null default 40,
  max_break_minutes integer not null default 60,
  late_tolerance_minutes integer not null default 5,
  early_clock_in_minutes integer not null default 15,
  geofence_required integer not null default 0,
  updated_at timestamptz not null default timezone('utc', now()),
  constraint chk_geofence_required check (geofence_required in (0, 1))
);

create table if not exists public.timesheet_approvals (
  id bigint generated by default as identity primary key,
  tenant_id varchar(64) not null,
  employee_id bigint not null references public.employees(id) on delete cascade,
  period_start timestamptz not null,
  period_end timestamptz not null,
  status varchar(32) not null default 'pending',
  approved_by varchar(255) not null default '',
  approved_at timestamptz null,
  constraint uq_timesheet_period unique (tenant_id, employee_id, period_start, period_end),
  constraint chk_timesheet_status check (status in ('pending', 'approved', 'rejected'))
);

create table if not exists public.manager_alerts (
  id bigint generated by default as identity primary key,
  tenant_id varchar(64) not null,
  employee_id bigint null references public.employees(id) on delete set null,
  alert_type varchar(64) not null,
  message varchar(500) not null,
  resolved integer not null default 0,
  created_at timestamptz not null default timezone('utc', now()),
  constraint chk_alert_resolved check (resolved in (0, 1))
);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  tenant_id varchar(64) not null,
  actor varchar(255) not null,
  action varchar(128) not null,
  details varchar(2000) not null default '',
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  tenant_id varchar(64) not null,
  from_user_id bigint not null references public.users(id) on delete cascade,
  to_user_id bigint not null references public.users(id) on delete cascade,
  text varchar(2000) not null,
  created_at timestamptz not null default timezone('utc', now()),
  read_at timestamptz null
);

create index if not exists idx_messages_tenant_pair_created on public.messages(tenant_id, from_user_id, to_user_id, created_at);

create or replace function public.adjust_inventory_item(
  p_tenant_id varchar,
  p_item_id bigint,
  p_change_amount integer,
  p_reason varchar,
  p_performed_by varchar
)
returns setof public.inventory_items
language plpgsql
security definer
as $$
declare
  v_item public.inventory_items%rowtype;
  v_next_qty integer;
begin
  if p_change_amount = 0 then
    raise exception 'change_amount cannot be zero' using errcode = '23514';
  end if;

  select *
  into v_item
  from public.inventory_items
  where id = p_item_id and tenant_id = p_tenant_id
  for update;

  if not found then
    raise exception 'Inventory item not found' using errcode = '23503';
  end if;

  v_next_qty := v_item.quantity_on_hand + p_change_amount;
  if v_next_qty < 0 then
    raise exception 'Adjustment would result in negative stock' using errcode = '23514';
  end if;

  update public.inventory_items
  set quantity_on_hand = v_next_qty,
      updated_at = timezone('utc', now())
  where id = v_item.id;

  insert into public.inventory_movements (item_id, tenant_id, change_amount, reason, performed_by)
  values (v_item.id, p_tenant_id, p_change_amount, p_reason, coalesce(p_performed_by, ''));

  return query
  select *
  from public.inventory_items
  where id = v_item.id;
end;
$$;

drop trigger if exists set_inventory_items_updated_at on public.inventory_items;
create trigger set_inventory_items_updated_at
before update on public.inventory_items
for each row execute function public.set_updated_at();

drop trigger if exists set_pos_menu_categories_updated_at on public.pos_menu_categories;
create trigger set_pos_menu_categories_updated_at
before update on public.pos_menu_categories
for each row execute function public.set_updated_at();

drop trigger if exists set_pos_menu_items_updated_at on public.pos_menu_items;
create trigger set_pos_menu_items_updated_at
before update on public.pos_menu_items
for each row execute function public.set_updated_at();

drop trigger if exists set_pos_tables_updated_at on public.pos_tables;
create trigger set_pos_tables_updated_at
before update on public.pos_tables
for each row execute function public.set_updated_at();

drop trigger if exists set_pos_tickets_updated_at on public.pos_tickets;
create trigger set_pos_tickets_updated_at
before update on public.pos_tickets
for each row execute function public.set_updated_at();

drop trigger if exists set_pos_ticket_items_updated_at on public.pos_ticket_items;
create trigger set_pos_ticket_items_updated_at
before update on public.pos_ticket_items
for each row execute function public.set_updated_at();

drop trigger if exists set_time_policies_updated_at on public.time_policies;
create trigger set_time_policies_updated_at
before update on public.time_policies
for each row execute function public.set_updated_at();

alter table public.tenant_apps enable row level security;
alter table public.users enable row level security;
alter table public.tenant_memberships enable row level security;
alter table public.pos_menu_categories enable row level security;
alter table public.pos_menu_items enable row level security;
alter table public.pos_tables enable row level security;
alter table public.pos_tickets enable row level security;
alter table public.pos_ticket_items enable row level security;
alter table public.pos_ticket_prints enable row level security;
alter table public.inventory_items enable row level security;
alter table public.inventory_movements enable row level security;
alter table public.employees enable row level security;
alter table public.time_events enable row level security;
alter table public.shifts enable row level security;
alter table public.time_policies enable row level security;
alter table public.timesheet_approvals enable row level security;
alter table public.manager_alerts enable row level security;
alter table public.audit_logs enable row level security;
alter table public.messages enable row level security;

create or replace function public.same_tenant_access(target_tenant_id varchar)
returns boolean
language sql
stable
as $$
  select exists (
    select 1
    from public.tenant_memberships membership
    where membership.user_id = coalesce(nullif(auth.jwt() ->> 'app_user_id', '')::bigint, -1)
      and membership.tenant_id = target_tenant_id
      and membership.is_active = 1
  );
$$;

drop policy if exists tenant_apps_tenant_select on public.tenant_apps;
create policy tenant_apps_tenant_select on public.tenant_apps for select using (public.same_tenant_access(tenant_id));
drop policy if exists users_tenant_select on public.users;
create policy users_tenant_select on public.users for select using (public.same_tenant_access(tenant_id));
drop policy if exists tenant_memberships_tenant_select on public.tenant_memberships;
create policy tenant_memberships_tenant_select on public.tenant_memberships for select using (public.same_tenant_access(tenant_id));
drop policy if exists pos_menu_categories_tenant_select on public.pos_menu_categories;
create policy pos_menu_categories_tenant_select on public.pos_menu_categories for select using (public.same_tenant_access(tenant_id));
drop policy if exists pos_menu_items_tenant_select on public.pos_menu_items;
create policy pos_menu_items_tenant_select on public.pos_menu_items for select using (public.same_tenant_access(tenant_id));
drop policy if exists pos_tables_tenant_select on public.pos_tables;
create policy pos_tables_tenant_select on public.pos_tables for select using (public.same_tenant_access(tenant_id));
drop policy if exists pos_tickets_tenant_select on public.pos_tickets;
create policy pos_tickets_tenant_select on public.pos_tickets for select using (public.same_tenant_access(tenant_id));
drop policy if exists pos_ticket_items_tenant_select on public.pos_ticket_items;
create policy pos_ticket_items_tenant_select on public.pos_ticket_items for select using (public.same_tenant_access(tenant_id));
drop policy if exists pos_ticket_prints_tenant_select on public.pos_ticket_prints;
create policy pos_ticket_prints_tenant_select on public.pos_ticket_prints for select using (public.same_tenant_access(tenant_id));
drop policy if exists inventory_items_tenant_select on public.inventory_items;
create policy inventory_items_tenant_select on public.inventory_items for select using (public.same_tenant_access(tenant_id));
drop policy if exists inventory_movements_tenant_select on public.inventory_movements;
create policy inventory_movements_tenant_select on public.inventory_movements for select using (public.same_tenant_access(tenant_id));
drop policy if exists employees_tenant_select on public.employees;
create policy employees_tenant_select on public.employees for select using (public.same_tenant_access(tenant_id));
drop policy if exists time_events_tenant_select on public.time_events;
create policy time_events_tenant_select on public.time_events for select using (public.same_tenant_access(tenant_id));
drop policy if exists shifts_tenant_select on public.shifts;
create policy shifts_tenant_select on public.shifts for select using (public.same_tenant_access(tenant_id));
drop policy if exists time_policies_tenant_select on public.time_policies;
create policy time_policies_tenant_select on public.time_policies for select using (public.same_tenant_access(tenant_id));
drop policy if exists timesheet_approvals_tenant_select on public.timesheet_approvals;
create policy timesheet_approvals_tenant_select on public.timesheet_approvals for select using (public.same_tenant_access(tenant_id));
drop policy if exists manager_alerts_tenant_select on public.manager_alerts;
create policy manager_alerts_tenant_select on public.manager_alerts for select using (public.same_tenant_access(tenant_id));
drop policy if exists audit_logs_tenant_select on public.audit_logs;
create policy audit_logs_tenant_select on public.audit_logs for select using (public.same_tenant_access(tenant_id));
drop policy if exists messages_tenant_select on public.messages;
create policy messages_tenant_select on public.messages for select using (public.same_tenant_access(tenant_id));
